# This config file describes an experiment.
# An experiment is "a collection of samples that need to be processed and analyzed together."

# experiment:
# * processing (optional, we may already have fastqs)
# * analysis   (optional, if the processing is bc2lfastq)

# These things are global; they do not change on a per-sample basis.
experiment:
  bcl2fastq_version: "2.20.0"      # Determines what image to run
  cellranger_version: "2.2.0"      # Determines what image to run
  sequencing_runs:                 # Metadata; used to generate the
                                   # experiment name.
                                   # E.g. "runtinybcl_himc0_111618-runtinybcl47_himc2_111618"
                                   # Sequencing run names are
                                   # separated by '-'.
    - id: tinybcl
      himc_pool: "0"
      date: "2018-11-16"
      bcl_filename: cellranger-tiny-bcl-1.2.0.tar.gz # TODO: should
                                                     # this be here?
                                                     # or should it be
                                                     # specified
                                                     # separately down
                                                     # with the other
                                                     # mkfastq stuff?
    # - id: tinybcl2
    #   himc_pool: "0"
    #   date: "2018-11-16"
                                   # TODO: should this be formatted differently?
  # name: runtinybcl_himc0_111618  # Generated; corresponds exactly
  #                                # to locations in:
  #                                # * s3://10x-data-backup/${experiment_name}/
  #                                # * s3://10x-pipeline/configs/${experiment_name}.yml
  #                                # composed of, underscore separated:
  #                                # * run
  #                                # * himc pool number
  #                                # * sequencing date (mmddyy)
  meta:
    debug: true # boolean; defaults to false

# Either
# * Nothing
# * bc2lfastq
# * mkfastq
# * mkfastq & bc2lfastq
processing:
  mkfastq:
    samples:
      - name: test_sample
        index_location: SI-P03-C9
      - name: test_sample_2
        index_location: SI-P03-C9

analyses:
  samples:
    - name: test_sample                       # Argument passed directly to `cellranger {count,vdj}`
      job_type: count                         # One of:
                                              # * count
                                              # * vdj
      chemistry: auto                         # Argument passed directly to `cellranger {count,vdj}`, optional; it's okay if it's null
      reference_transcriptome:
        name: GRCh38                          # Argument passed directly to `cellranger {count,vdj}`
        version: 1.2.0                        # Argument passed directly to `cellranger {count,vdj}`
      target_cell_count: 100                  # Argument passed to `cellranger count`
      feature_barcoding: False                # Will help us determine if this is a feature barcoding experiment in which case we'll need to generate more samplesheets
      pooled_run: False                       # Will help us determine if we need to wait for 2 sets of fastqs, each from different sequencing runs, to run cellranger count

    - name: test_sample_2
      job_type: count
      chemistry: auto
      reference_transcriptome:
        name: GRCh38
        version: 1.2.0
      target_cell_count: 100
      feature_barcoding: False
      pooled_run: False
