# This config file describes an experiment.
# An experiment is "a collection of samples that need to be processed and analyzed together."

# The information under `experiment` is global; it does not change on a per-sample basis.
experiment:
  bcl2fastq_version: "2.20.0"      # Determines what image to run. Current Options: 2.20.10
  cellranger_version: "3.0.2"      # Determines what image to run Current Options: 2.2.0, 3.0.2
  # sequencing_runs metadata is used to generate the experiment name.
  # Based off the `sequencing_runs` data below, our generated experiment name would
  # be "run1_himc1_032519-run2_himc2_032519"
  # Sequencing run names are separated by '-'. We may have 1 or more sequencing
  # runs. When there is more than 1 run, we refer to them as "pooled runs"
  sequencing_runs:
    - id: 1
      himc_pool: 1
      date: "2019-03-25"
      bcl_file: "190325_NB501426_0271_AH2J72BGXB.tar.gz"
  meta:
    debug: true # boolean; defaults to false

# Either
# * Nothing
# * bcl2fastq
# * mkfastq
# * mkfastq & bcl2fastq
processing:
  mkfastq:
    samples:
      - name: 7002v3A
        index_location: SI-GA-E12
      - name: 7002v3B
        index_location: SI-GA-E11
  bcl2fastq:
    samples:
      - name: 7002v3A-A
        index_location: RPI9
      - name: 7002v3A-H
      # The `_s` suffix here is necessary so that we can accurately match the index_location
      # to a proper sequence in from our citeseq_sample_indices.csv file
        index_location: D709_s
      - name: 7002v3B-A
        index_location: RPI10
      - name: 7002v3B-H
      # The `_s` suffix here is necessary so that we can accurately match the index_location
      # to a proper sequence from our citeseq_sample_indices.csv file
        index_location: D710_s

analyses:
  samples:
    - name: 7002v3A
      job_type: count # may be count or vdj
      # a defauly chemistry of auto is usually sufficient to run cellranger count;
      # however, if errors are thrown, you may specify the chemistry
      # as per the 10x documentation: https://support.10xgenomics.com/single-cell-gene-expression/software/pipelines/latest/using/count
      chemistry: auto
      reference_transcriptome:
        # may also be hg19, mm10, or vdj; see 10x-pipeline/reference_transcriptome
        # s3 bucket for currently available options for name and version. You may also reference
        # ./docs/Building_the_Pipeline.md
        name: GRCh38
        version: 1.2.0
      target_cell_count: 10000
      feature_barcoding:
        enabled: False # will be True if we're performing feature barcoding
      pooled_run: False # will be False if we only have 1 sequencing run
      - name: 7002v3B
      job_type: count
      chemistry: auto
      reference_transcriptome:
        name: GRCh38
        version: 1.2.0
      target_cell_count: 10000
      feature_barcoding:
        enabled: False
      pooled_run: False
